version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestaopredial
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/gestaopredial
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5000:5000"

volumes:
  dbdata:
